# Generated by Django 5.0.6 on 2024-08-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('project_status', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
            ],
        ),
    ]
