# Generated by Django 5.0.6 on 2024-08-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
    ]
