# Generated by Django 5.0.6 on 2024-08-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('HR', 'Human Resource'), ('BD', 'Business Development'), ('SE', 'Software Developer'), ('QA', 'Quality Assurance'), ('PM', 'Product Manager')], max_length=200)),
                ('date_of_join', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='teams.team')),
            ],
        ),
    ]
