# Generated by Django 5.0.6 on 2024-08-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_type'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('HR', 'Human Resource'), ('BD', 'Business Development'), ('SE', 'Software Developer'), ('QA', 'Quality Assurance'), ('PM', 'Product Manager')], max_length=200),
        ),
    ]
