# Generated by Django 5.0.6 on 2024-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_team_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Human Resource', 'Human Resource'), ('Business Development', 'Business Development'), ('Software Engineer', 'Software Developer'), ('Quality Assurance', 'Quality Assurance'), ('Product Manager', 'Product Manager')], max_length=200),
        ),
    ]
