# Generated by Django 5.0.6 on 2024-08-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('HR', 'Human Resource'), ('BD', 'Business Development'), ('SE', 'Software Developer'), ('QA', 'Quality Assurance'), ('PM', 'Product Manager')], max_length=200),
        ),
    ]
